# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='First name')),
                ('surname', models.CharField(max_length=50, verbose_name='Second name')),
                ('date_birth', models.DateField(verbose_name='Date of Birth')),
                ('bio', models.TextField(max_length=1000, verbose_name='bio')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('jabber_id', models.CharField(max_length=255, verbose_name='Jabber ID')),
                ('skype_id', models.CharField(max_length=255, verbose_name='Skype ID')),
                ('other_contacts', models.TextField(max_length=255, verbose_name='Others contacts')),
            ],
            options={
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
